name: CI

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'ChangeLog'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CC: [gcc, clang]
    env:
      make_options: 'CC=${{ matrix.CC }}'
    steps:
    - uses: actions/checkout@v3
    - run: make -n $make_options
    - name: make
      run: make $make_options
    - name: make check
      run: make check
