name: CI

on:
  push:
    paths:
      - '**.h'
      - '**.c'
      - '**.cpp'
      - 'Makefile'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        CC: [gcc, clang]
        OPTIM: [-O2]
    env:
      make_options: 'CC=${{ matrix.CC }} OPTIM=${{ matrix.OPTIM }}'
    steps:
    - uses: actions/checkout@v2
    - run: make -n $make_options
    - run: make $make_options
    - run: make check
