on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        CC: [gcc, clang]
        OPTIM: [-Og, -O2]

    env:
      make_options: 'CC=${{ matrix.CC }} OPTIM=${{ matrix.OPTIM }}'

    steps:
    - uses: actions/checkout@v2
    - run: make -n $make_options
    - run: make $make_options
    - run: make check $make_options
